export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const ADD_GET_FRIENDS_FAILURE = 'ADD_GET_FRIENDS_FAILURE'
export const ADD_GET_FRIENDS_SUCCESS = 'ADD_GET_FRIENDS_SUCCESS'
export const ADD_GET_FRIENDS_LOADING = 'ADD_GET_FRIENDS_LOADING'
